COINES_INSTALL_PATH = ../lib

EXAMPLE_FILE = set-shuttle-board.c

C_SRCS += $(COINES_INSTALL_PATH)/coines_ext/coines_ext.c

INCLUDEPATHS += \
$(COINES_INSTALL_PATH)/coinesAPI/pc \
$(COINES_INSTALL_PATH)/coinesAPI/pc/comm_driver \
$(COINES_INSTALL_PATH)/coinesAPI/pc/comm_intf \

INCLUDEPATHS += $(COINES_INSTALL_PATH)/coines_ext

include $(COINES_INSTALL_PATH)/examples.mk
